In [2]:
import pandas as pd
df = pd.read_csv('military_raw_data (1).csv')
df.head()

,Country,total-population-by-country,available-military-manpower,manpower-fit-for-military-service,manpower-reaching-military-age-annually,active-military-manpower,active-reserve-military-manpower,manpower-paramilitary,aircraft-total,aircraft-total-fighters,...,proven-natural-gas-reserves-by-country,coal-production-by-country,coal-consumption-by-country,proven-coal-reserves-by-country,square-land-area,coastline-coverage,border-coverage,waterway-coverage,Capital,Captal Population
0,China,"1,415,043,270","764,123,366","626,864,169","19,810,606","2,035,000","510,000","625,000","3,309","1,212",...,"6,654,000,000,000 \t\t\...","4,827,000,000 \t\t\t\t\...","5,313,000,000 \t\t\t\t\...","143,197,000,000 \t\t\t\...","9,596,960 \t\t\t\t\t\t\...","14,500 \t\t\t\t\t\t\r\n...","22,457 \t\t\t\t\t\t\r\n...","27,700 \t\t\t\t\t\t\r\n...",Tokyo,"37,274,000"
1,India,"1,409,128,296","662,290,299","522,786,598","23,955,181","1,455,550","1,155,000","2,527,000","2,229",513,...,"1,381,000,000,000 \t\t\...","985,671,000 \t\t\t\t\t\...","1,200,000,000 \t\t\t\t\...","111,052,000,000 \t\t\t\...","3,287,263 \t\t\t\t\t\t\...","7,000 \t\t\t\t\t\t\r\n\...","13,888 \t\t\t\t\t\t\r\n...","14,500 \t\t\t\t\t\t\r\n...",New Delhi,"32,066,000"
2,United States,"341,963,408","150,463,900","124,816,644","4,445,524","1,328,000","799,500",0,"13,043","1,790",...,"13,402,000,000,000 \t\t...","548,849,000 \t\t\t\t\t\...","476,044,000 \t\t\t\t\t\...","248,941,000,000 \t\t\t\...","9,833,517 \t\t\t\t\t\t\...","19,924 \t\t\t\t\t\t\r\n...","12,002 \t\t\t\t\t\t\r\n...","41,009 \t\t\t\t\t\t\r\n...",Dhaka,"22,478,000"
3,Indonesia,"281,562,465","137,965,608","114,595,923","4,786,562","400,000","400,000","250,000",459,41,...,"1,408,000,000,000 \t\t\...","659,357,000 \t\t\t\t\t\...","202,283,000 \t\t\t\t\t\...","34,869,000,000 \t\t\t\t...","1,904,569 \t\t\t\t\t\t\...","54,716 \t\t\t\t\t\t\r\n...","2,958 \t\t\t\t\t\t\r\n\...","21,579 \t\t\t\t\t\t\r\n...",Mexico City,"22,281,000"
4,Pakistan,"252,363,571","108,516,336","85,803,614","4,794,908","654,000","550,000","500,000","1,399",328,...,"592,219,000,000 \t\t\t\...","12,712,000 \t\t\t\t\t\t...","34,027,000 \t\t\t\t\t\t...","3,064,000,000 \t\t\t\t\...","796,095 \t\t\t\t\t\t\r\...","1,046 \t\t\t\t\t\t\r\n\...","7,257 \t\t\t\t\t\t\r\n\...",0 \t\t\t\t\t\t\r\n\t\t\...,Cairo,"21,750,000"

In [3]:
df = df.replace({',': '', '%': '','	$ ':''}, regex=True)

In [4]:
df.columns = df.columns.str.lower().str.replace('-', '_')

In [5]:
df = df.rename(columns={
    'captal_population': 'capital_population'
})

In [6]:
def clean_units(col):

    if col.dtype == "object" and col.str.contains(r"\d", regex=True, na=False).any():
        return (
            col
            .str.replace(",", "", regex=False)
            .str.extract(r"([-+]?\d*\.?\d+)")[0]
        )
    return col

df = df.apply(clean_units)
df = df.apply(pd.to_numeric, errors="ignore")

/tmp/ipython-input-2056631321.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

In [7]:
df.isnull().sum()

country                                     0
total_population_by_country                 0
available_military_manpower                 0
manpower_fit_for_military_service           0
manpower_reaching_military_age_annually     0
active_military_manpower                    0
active_reserve_military_manpower            0
manpower_paramilitary                       0
aircraft_total                              0
aircraft_total_fighters                     0
aircraft_total_attack_types                 0
aircraft_total_transports                   0
aircraft_total_trainers                     0
aircraft_total_special_mission              0
aircraft_total_tanker_fleet                 0
aircraft_helicopters_total                  0
aircraft_helicopters_attack                 0
armor_tanks_total                           0
armor_apc_total                             0
armor_self_propelled_guns_total             0
armor_towed_artillery_total                 0
armor_mlrs_total                            0
navy_ships                                  0
navy_force_by_tonnage                      98
navy_aircraft_carriers                      0
navy_helo_carriers                          0
navy_submarines                             0
navy_destroyers                             0
navy_frigates                               0
navy_corvettes                              0
navy_patrol_coastal_craft                   0
navy_mine_warfare_craft                     0
defense_spending_budget                     0
external_debt_by_country                    0
purchasing_power_parity                     0
reserves_of_foreign_exchange_and_gold       0
major_serviceable_airports_by_country       0
labor_force_by_country                      0
major_ports_and_terminals                   0
railway_coverage                            0
roadway_coverage                            0
oil_production_by_country                   0
oil_consumption_by_country                  0
proven_oil_reserves_by_country              0
natural_gas_production_by_country           0
natural_gas_consumption_by_country          0
proven_natural_gas_reserves_by_country      0
coal_production_by_country                  0
coal_consumption_by_country                 0
proven_coal_reserves_by_country             0
square_land_area                            0
coastline_coverage                          0
border_coverage                             0
waterway_coverage                           0
capital                                     0
captal population                           0
dtype: int64

In [22]:
df=df.fillna(0)

In [24]:
df["navy_force_by_tonnage"] = df["navy_force_by_tonnage"].astype(int)

In [26]:
df.to_csv("military_cleaned.csv", index=False)