# Module 2: Data Cleaning and Structuring

In [3]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv(r"C:\Users\avach\Downloads\Sc_global_firepower_data_2025.csv")
df.head()

,rank,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,natural_gas_production_cum,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km
0,1,United States,341963408,150463900,124816644,4445524,1328000,799500,0,13043,...,1.029000e+12,9.143010e+11,1.340200e+13,548849000,476044000,2.489410e+11,9833517,19924,12002,41009
1,2,Russia,140820810,69002197,46189226,1267387,1320000,2000000,250000,4292,...,6.178300e+11,4.722390e+11,4.780500e+13,508190000,310958000,1.621660e+11,17098242,37653,22407,102000
2,3,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3309,...,2.253410e+11,3.661600e+11,6.654000e+12,4827000000,5313000000,1.431970e+11,9596960,14500,22457,27700
3,4,India,1409128296,662290299,522786598,23955181,1455550,1155000,2527000,2229,...,3.317000e+10,5.886700e+10,1.381000e+12,985671000,1200000000,1.110520e+11,3287263,7000,13888,14500
4,5,South Korea,52081799,26040900,21353538,416654,600000,3100000,120000,1592,...,5.512700e+07,5.948000e+10,7.079000e+09,15595000,136413000,3.260000e+08,99720,2413,237,1600

In [11]:
df.tail()

,rank,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,natural_gas_production_cum,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km
140,141,Kosovo,1977093,917371,743387,17794,10000,5000,500,0,...,0.0,0.0,0.000000e+00,9074000,8927000,1.564000e+09,10887,0,714,0
141,142,Somalia,13017273,2993973,1796384,130173,15000,0,2000,0,...,0.0,0.0,5.663000e+09,0,0,0.000000e+00,637657,3025,2385,0
142,143,Central African Republic,5650957,2203873,1254512,101717,10000,0,1000,6,...,0.0,0.0,0.000000e+00,0,0,3.000000e+06,622984,0,5920,2800
143,144,Benin,14697052,5584880,3189260,308638,4750,0,0,5,...,0.0,182131000.0,1.133000e+09,0,45000,0.000000e+00,112622,121,2123,150
144,145,Bhutan,884546,203446,122067,4423,7500,0,0,2,...,0.0,0.0,0.000000e+00,177000,325000,0.000000e+00,38394,0,1136,0

In [15]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace("__", "_")
)
df.columns

Index(['rank', 'country', 'total_population', 'total_military_manpower',
       'fit_for_service', 'population_reaching_military_age_annually',
       'active_personnel', 'reserve_personnel', 'paramilitary',
       'total_military_aircraft', 'fighter_aircraft', 'attack_aircraft',
       'transport_aircraft', 'trainer_aircraft', 'special_mission_aircraft',
       'tanker_aircraft', 'total_military_helicopters', 'attack_helicopters',
       'tanks', 'armored_fighting_vehicles', 'self_propelled_artillery',
       'towed_artillery', 'rocket_projectors', 'total_naval_fleet',
       'total_naval_fleet_tonnage_mt', 'aircraft_carriers',
       'helicopter_carriers', 'submarines', 'destroyers', 'frigates',
       'corvettes', 'coastal_patrol_craft', 'mine_warfare_craft',
       'defense_budget_usd', 'external_debt_usd',
       'purchasing_power_parity_usd', 'foreign_exchange_and_gold_reserves_usd',
       'total_serviceable_airports', 'labour_force',
       'major_ports_and_terminals', 'total_merchant_marine_fleet',
       'railway_coverage_km', 'roadway_coverage_km', 'oil_production_bbl',
       'oil_consumption_bbl', 'proven_oil_reserves_bbl',
       'natural_gas_production_cum', 'natural_gas_consumption_cum',
       'proven_natural_gas_reserves_cum', 'coal_production_cum',
       'coal_consumption_mt', 'proven_coal_reserves_cum',
       'total_land_area_sq_km', 'coastline_coverage_km', 'border_coverage_km',
       'waterway_coverage_km'],
      dtype='object')

In [17]:
def clean_numeric(series):
    return (
        series.astype(str)
        .str.replace(r"[,%+$]", "", regex=True)
        .str.replace(" ", "")
        .replace("nan", np.nan)
    )

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = clean_numeric(df[col])

In [21]:
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except (ValueError, TypeError):
        pass

In [23]:
missing_percent = df.isnull().mean() * 100
missing_percent.sort_values(ascending=False)

total_naval_fleet_tonnage_mt                 67.586207
rank                                          0.000000
frigates                                      0.000000
coastal_patrol_craft                          0.000000
mine_warfare_craft                            0.000000
defense_budget_usd                            0.000000
external_debt_usd                             0.000000
purchasing_power_parity_usd                   0.000000
foreign_exchange_and_gold_reserves_usd        0.000000
total_serviceable_airports                    0.000000
labour_force                                  0.000000
major_ports_and_terminals                     0.000000
total_merchant_marine_fleet                   0.000000
railway_coverage_km                           0.000000
roadway_coverage_km                           0.000000
oil_production_bbl                            0.000000
oil_consumption_bbl                           0.000000
proven_oil_reserves_bbl                       0.000000
natural_gas_production_cum                    0.000000
natural_gas_consumption_cum                   0.000000
proven_natural_gas_reserves_cum               0.000000
coal_production_cum                           0.000000
coal_consumption_mt                           0.000000
proven_coal_reserves_cum                      0.000000
total_land_area_sq_km                         0.000000
coastline_coverage_km                         0.000000
border_coverage_km                            0.000000
corvettes                                     0.000000
destroyers                                    0.000000
country                                       0.000000
trainer_aircraft                              0.000000
total_population                              0.000000
total_military_manpower                       0.000000
fit_for_service                               0.000000
population_reaching_military_age_annually     0.000000
active_personnel                              0.000000
reserve_personnel                             0.000000
paramilitary                                  0.000000
total_military_aircraft                       0.000000
fighter_aircraft                              0.000000
attack_aircraft                               0.000000
transport_aircraft                            0.000000
special_mission_aircraft                      0.000000
submarines                                    0.000000
tanker_aircraft                               0.000000
total_military_helicopters                    0.000000
attack_helicopters                            0.000000
tanks                                         0.000000
armored_fighting_vehicles                     0.000000
self_propelled_artillery                      0.000000
towed_artillery                               0.000000
rocket_projectors                             0.000000
total_naval_fleet                             0.000000
aircraft_carriers                             0.000000
helicopter_carriers                           0.000000
waterway_coverage_km                          0.000000
dtype: float64

In [27]:
for col in df.columns:
    if pd.api.types.is_numeric_dtype(df[col]):
        df[col] = df[col].fillna(df[col].median())
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

In [33]:
df.isnull().sum().sort_values(ascending=False).head()

rank                    0
country                 0
corvettes               0
coastal_patrol_craft    0
mine_warfare_craft      0
dtype: int64

In [31]:
(df.isnull().mean() * 100).max()

0.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 56 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   rank                                       145 non-null    int64
 1   country                                    145 non-null    object
 2   total_population                           145 non-null    int64
 3   total_military_manpower                    145 non-null    int64
 4   fit_for_service                            145 non-null    int64
 5   population_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                           145 non-null    int64
 7   reserve_personnel                          145 non-null    int64
 8   paramilitary                               145 non-null    int64
 9   total_military_aircraft                    145 non-null    int64
 10  fighter_aircraft                           145 non-null    int64
 11  attack_aircraft                            145 non-null    int64
 12  transport_aircraft                         145 non-null    int64
 13  trainer_aircraft                           145 non-null    int64
 14  special_mission_aircraft                   145 non-null    int64
 15  tanker_aircraft                            145 non-null    int64
 16  total_military_helicopters                 145 non-null    int64
 17  attack_helicopters                         145 non-null    int64
 18  tanks                                      145 non-null    int64
 19  armored_fighting_vehicles                  145 non-null    int64
 20  self_propelled_artillery                   145 non-null    int64
 21  towed_artillery                            145 non-null    int64
 22  rocket_projectors                          145 non-null    int64
 23  total_naval_fleet                          145 non-null    int64
 24  total_naval_fleet_tonnage_mt               145 non-null    float64
 25  aircraft_carriers                          145 non-null    int64
 26  helicopter_carriers                        145 non-null    int64
 27  submarines                                 145 non-null    int64
 28  destroyers                                 145 non-null    int64
 29  frigates                                   145 non-null    int64
 30  corvettes                                  145 non-null    int64
 31  coastal_patrol_craft                       145 non-null    int64
 32  mine_warfare_craft                         145 non-null    int64
 33  defense_budget_usd                         145 non-null    float64
 34  external_debt_usd                          145 non-null    float64
 35  purchasing_power_parity_usd                145 non-null    float64
 36  foreign_exchange_and_gold_reserves_usd     145 non-null    float64
 37  total_serviceable_airports                 145 non-null    int64
 38  labour_force                               145 non-null    int64
 39  major_ports_and_terminals                  145 non-null    int64
 40  total_merchant_marine_fleet                145 non-null    int64
 41  railway_coverage_km                        145 non-null    int64
 42  roadway_coverage_km                        145 non-null    int64
 43  oil_production_bbl                         145 non-null    int64
 44  oil_consumption_bbl                        145 non-null    int64
 45  proven_oil_reserves_bbl                    145 non-null    float64
 46  natural_gas_production_cum                 145 non-null    float64
 47  natural_gas_consumption_cum                145 non-null    float64
 48  proven_natural_gas_reserves_cum            145 non-null    float64
 49  coal_production_cum                        145 non-null    int64
 50  coal_consumption_mt                        145 non-null    int64
 51  proven_coal_reserves_cum                   145 non-null    float64
 52  total_land_area_sq_km                      145 non-null    int64
 53  coastline_coverage_km                      145 non-null    int64
 54  border_coverage_km                         145 non-null    int64
 55  waterway_coverage_km                       145 non-null    int64
dtypes: float64(10), int64(45), object(1)
memory usage: 63.6+ KB

In [37]:
df.to_csv("military_1cleaned.csv", index=False)