In [169]:
import pandas as pd
import numpy as np

In [171]:
df=pd.read_csv(r"C:\Users\avach\Downloads\processed_dataset.csv")
work_df = df.copy()

In [173]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace("__", "_")
)
df.columns

Index(['power_index_rank', 'country', 'capital_city', 'continent', 'alliance',
       'year', 'region', 'population', 'total_military_manpower',
       'fit_for_service', 'population_reaching_military_age_annually',
       'active_personnel', 'reserve_personnel', 'total_personnel',
       'paramilitary', 'total_aircraft', 'military_aircraft',
       'fighter_aircraft', 'attack_aircraft', 'transport_aircraft',
       'trainer_aircraft', 'special_mission_aircraft', 'tanker_aircraft',
       'total_helicopters', 'total_military_helicopters', 'attack_helicopters',
       'tanks', 'armored_vehicles', 'artillery_units',
       'self_propelled_artillery', 'towed_artillery', 'rocket_projectors',
       'naval_assets', 'total_naval_fleet_tonnage_mt', 'aircraft_carriers',
       'helicopter_carriers', 'submarines', 'destroyers', 'frigates',
       'corvettes', 'coastal_patrol_craft', 'mine_warfare_craft',
       'defense_budget_usd', 'external_debt_usd',
       'purchasing_power_parity_usd', 'foreign_exchange_and_gold_reserves_usd',
       'total_serviceable_airports', 'labour_force',
       'major_ports_and_terminals', 'total_merchant_marine_fleet',
       'railway_coverage_km', 'roadway_coverage_km', 'oil_production_bbl',
       'oil_consumption_bbl', 'proven_oil_reserves_bbl',
       'natural_gas_production_cum', 'natural_gas_consumption_cum',
       'proven_natural_gas_reserves_cum', 'coal_production_cum',
       'coal_consumption_mt', 'proven_coal_reserves_cum', 'land_area_sq_km',
       'coastline_km', 'border_coverage_km', 'waterway_coverage_km',
       'gdp_usd'],
      dtype='object')

In [175]:
df[["total_aircraft", "tanks", "naval_assets", "population"]].dtypes

total_aircraft    int64
tanks             int64
naval_assets      int64
population        int64
dtype: object

In [177]:
df["total_aircraft"].head()
df["total_aircraft"].dtype

dtype('int64')

In [179]:
numeric_cols = [
    "total_aircraft", "tanks", "naval_assets",
    "population", "defense_budget_usd", "gdp_usd",
    "total_personnel", "active_personnel",
    "land_area_sq_km", "coastline_km", "power_index_rank"
]

for col in numeric_cols:
    if col in work_df.columns:
        work_df[col] = (
            work_df[col]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.replace("+", "", regex=False)
            .str.strip()
        )
        work_df[col] = pd.to_numeric(work_df[col], errors="coerce")

In [181]:
df.head()

,power_index_rank,country,capital_city,continent,alliance,year,region,population,total_military_manpower,fit_for_service,...,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,land_area_sq_km,coastline_km,border_coverage_km,waterway_coverage_km,gdp_usd
0,1,United States,"Washington, D.C.",North America,NATO,2025,North America,341963408,150463900,124816644,...,9.140000e+11,1.340000e+13,548849000,476044000,2.490000e+11,9833517,19924,12002,41009,3.060000e+13
1,2,Russia,Moscow,Europe,Non-NATO,2025,Asia,140820810,69002197,46189226,...,4.720000e+11,4.780000e+13,508190000,310958000,1.620000e+11,17098242,37653,22407,102000,2.540000e+12
2,3,China,Beijing,Asia,Non-NATO,2025,Asia,1415043270,764123366,626864169,...,3.660000e+11,6.650000e+12,4827000000,5313000000,1.430000e+11,9596960,14500,22457,27700,1.940000e+13
3,4,India,New Delhi,Asia,Non-NATO,2025,Asia,1409128296,662290299,522786598,...,5.886700e+10,1.380000e+12,985671000,1200000000,1.110000e+11,3287263,7000,13888,14500,4.130000e+12
4,5,South Korea,Seoul,Asia,Non-NATO,2025,Asia,52081799,26040900,21353538,...,5.948000e+10,7.079000e+09,15595000,136413000,3.260000e+08,99720,2413,237,1600,1.860000e+12

In [183]:
#Assets per Capita
work_df["assets_per_capita"] = (
    work_df["total_aircraft"] +
    work_df["tanks"] +
    work_df["naval_assets"]
) / work_df["population"]

In [185]:
work_df[["country", "assets_per_capita"]].head()

         country  assets_per_capita
0  United States           0.000075
1         Russia           0.000094
2          China           0.000009
3          India           0.000006
4    South Korea           0.000093

In [187]:
#Defense Budget to GDP Ratio
work_df["defense_budget_to_gdp"] = (
    work_df["defense_budget_usd"] / work_df["gdp_usd"]
)

In [189]:
work_df[["country", "assets_per_capita","defense_budget_to_gdp"]].head()

         country  assets_per_capita  defense_budget_to_gdp
0  United States           0.000075               0.029248
1         Russia           0.000094               0.049606
2          China           0.000009               0.013763
3          India           0.000006               0.018160
4    South Korea           0.000093               0.024892

In [191]:
#Personnel Density
work_df["personnel_density"] = (
    work_df["total_personnel"] / work_df["population"]
)

In [193]:
work_df[["country", "personnel_density"]].head()

         country  personnel_density
0  United States           0.006221
1         Russia           0.023576
2          China           0.001799
3          India           0.001853
4    South Korea           0.071042

In [195]:
#Defense Budget per Soldier
work_df["defense_budget_per_soldier"] = (
    work_df["defense_budget_usd"] / work_df["active_personnel"]
)

In [197]:
work_df[["country", "defense_budget_per_soldier"]].head()

         country  defense_budget_per_soldier
0  United States               673945.783133
1         Russia                95454.545455
2          China               131203.931204
3          India                51526.914225
4    South Korea                77166.666667

In [199]:
#Power Index Rank Gap (USA reference)
usa_rank = work_df.loc[
    work_df["country"] == "United States",
    "power_index_rank"
].iloc[0]

work_df["power_index_rank_gap"] = (
    work_df["power_index_rank"] - usa_rank
)

In [201]:
work_df[["country", "power_index_rank_gap"]].head()

         country  power_index_rank_gap
0  United States                     0
1         Russia                     1
2          China                     2
3          India                     3
4    South Korea                     4

In [203]:
#Air Power Ratio
work_df["air_power_ratio"] = (
    work_df["total_aircraft"] / work_df["active_personnel"]
)

In [205]:
work_df[["country", "air_power_ratio"]].head()

         country  air_power_ratio
0  United States         0.015466
1         Russia         0.005334
2          China         0.002803
3          India         0.002455
4    South Korea         0.004007

In [207]:
#Armor Intensity Index
work_df["armor_intensity_index"] = (
    work_df["tanks"] / work_df["land_area_sq_km"]
)

In [209]:
work_df[["country", "armor_intensity_index"]].head()

         country  armor_intensity_index
0  United States               0.000472
1         Russia               0.000336
2          China               0.000709
3          India               0.001278
4    South Korea               0.022423

In [211]:
#Naval Strength per Coastline
work_df["naval_strength_per_coastline"] = (
    work_df["naval_assets"] / work_df["coastline_km"]
)

In [226]:
work_df[["country", "naval_strength_per_coastline"]].head()

         country  naval_strength_per_coastline
0  United States                      0.022084
1         Russia                      0.011128
2          China                      0.052000
3          India                      0.041857
4    South Korea                      0.094074

In [230]:
#Military Burden Index
work_df["military_burden_index"] = (
    work_df["defense_budget_usd"] / work_df["population"]
)

In [232]:
work_df[["country", "military_burden_index"]].head()

         country  military_burden_index
0  United States            2617.239094
1         Russia             894.754121
2          China             188.686810
3          India              53.224394
4    South Korea             888.986189

In [234]:
#Coalition Strength Index (dynamic)
work_df["total_assets"] = (
    work_df["total_aircraft"] +
    work_df["tanks"] +
    work_df["naval_assets"]
)

In [236]:
work_df[["country", "total_assets"]].head()

         country  total_assets
0  United States         25619
1         Russia         13210
2          China         13259
3          India          8067
4    South Korea          4867

In [238]:
coalition_strength = work_df.loc[
    work_df["alliance"] == "NATO",
    "total_assets"
].sum()

In [242]:
KPI_df = work_df[
    [
        "country",
        "year",
        "assets_per_capita",
        "defense_budget_to_gdp",
        "personnel_density",
        "defense_budget_per_soldier",
        "power_index_rank_gap",
        "air_power_ratio",
        "armor_intensity_index",
        "naval_strength_per_coastline",
        "military_burden_index",
        "total_assets"
    ]
]

KPI_df.to_csv("military_derived_metrics(KPI).csv", index=False)